(() => {
  const script=document.currentScript,asset=new URL('./',script.src),site=script.dataset.site||'portfolio';
  const el=(tag,cls)=>{const n=document.createElement(tag);if(cls)n.className=cls;return n;};
  const root=el('div','biuret-guide');root.setAttribute('translate','no');document.body.append(root);
  const launcher=el('button','bg-launch');launcher.type='button';launcher.setAttribute('aria-haspopup','dialog');launcher.setAttribute('aria-expanded','false');
  const dialog=el('dialog','bg-panel');dialog.setAttribute('aria-labelledby','bg-title');
  const header=el('header','bg-header'),identity=el('div','bg-identity'),badge=el('span','bg-badge'),title=el('h2');title.id='bg-title';title.textContent='Biuret Guide';identity.append(badge,title);
  const close=el('button','bg-close');close.type='button';close.textContent='×';header.append(identity,close);
  const intro=el('p','bg-intro'),context=el('div','bg-context'),contextLabel=el('span'),contextName=el('strong');context.append(contextLabel,contextName);
  const suggestions=el('div','bg-suggestions'),conversation=el('div','bg-conversation');conversation.setAttribute('role','log');conversation.setAttribute('aria-live','polite');conversation.setAttribute('aria-relevant','additions');
  const consentLabel=el('label','bg-consent');consentLabel.hidden=true;const consent=el('input');consent.type='checkbox';const consentCopy=el('span');consentLabel.append(consent,consentCopy);
  const form=el('form','bg-form'),label=el('label'),input=el('input'),send=el('button');label.htmlFor='bg-question';input.id='bg-question';input.maxLength=500;input.required=true;input.minLength=2;input.autocomplete='off';input.dir='auto';send.type='submit';form.append(label,input,send);
  const status=el('p','bg-status');status.setAttribute('role','status');
  const actions=el('div','bg-actions'),retry=el('button','bg-retry'),clear=el('button','bg-retry'),pilot=el('a','bg-pilot');retry.type=clear.type='button';pilot.href='https://biuret.dev/guide-pilot.html';actions.append(retry,clear,pilot);
  const footer=el('div','bg-footer'),privacy=el('p','bg-privacy'),hint=el('span','bg-keyboard');footer.append(privacy,hint);
  dialog.append(header,intro,context,suggestions,conversation,consentLabel,form,status,actions,footer);root.append(launcher,dialog);
  let cards=[],core,gateway,readReply,configured=false,busy=false,checking=false,attempt=0,state='loading',access='',returnFocus=null,pendingTopic='';const exchanges=[];
  const en=()=>document.documentElement.lang!=='ar',tr=(a,b)=>en()?a:b,locale=()=>en()?'en':'ar';
  const questions={portfolio:[['Who owns this website?','مين صاحب هذا الموقع؟'],['What can I actually try today?','شو بقدر أجرب فعلياً اليوم؟'],['How do the three sites differ?','شو الفرق بين المواقع الثلاثة؟']],academy:[['Help me choose a specialty after foundations.','ساعدني أختار تخصص بعد الأساسيات.'],['How can I download my certificate?','كيف أنزّل شهادتي؟'],['Who created Biuret?','مين أنشأ Biuret؟']],playground:[['Which tool fits my task?','أي أداة تناسب مهمتي؟'],['Are the Desktop downloads available?','هل تنزيل البرامج المكتبية متاح؟'],['Who created Biuret?','مين أنشأ Biuret؟']]};
  const notices={loading:['Loading Guide…','جارٍ تحميل الدليل…'],search:['Gemini is composing your answer…','Gemini يصيغ إجابتك…'],remote:['Gemini · generated for your question. Check the sources.','Gemini · إجابة مصاغة لسؤالك. راجع المصادر.'],clarify:['Gemini needs a little more detail.','Gemini يحتاج توضيحاً بسيطاً.'],unknown:['Gemini has no documented answer yet. No saved reply was substituted.','لا يملك Gemini إجابة موثقة بعد. لم نستبدلها برد محفوظ.'],quota:['Usage limit reached. Wait a minute and send again. No saved answer was substituted.','بلغت حد الاستخدام. انتظر دقيقة وأعد الإرسال. لم نستبدل الإجابة برد جاهز.'],unavailable:['Gemini could not answer. Check connection and retry; no saved answer was substituted.','تعذّر رد Gemini. افحص الاتصال وأعد المحاولة؛ لم نستبدل الإجابة برد جاهز.'],error:['Guide information could not load. Reload below.','تعذّر تحميل معلومات الدليل. أعد تحميله أدناه.'],consent:['Check consent before sending to Gemini.','ضع علامة الموافقة قبل إرسال السؤال إلى Gemini.']};
  function sourceLink(card){const a=el('a','bg-source');a.href=core.sourceURL(card,site);a.textContent=card.title[locale()]+' ↗';return a;}
  function fillQuestion(question){input.value=question;input.focus();}
  function render(){
    root.dir=en()?'ltr':'rtl';dialog.classList.toggle('bg-has-answer',exchanges.length>0);
    launcher.textContent='✦ Biuret Guide';launcher.setAttribute('aria-label',tr('Open Biuret Guide · Ctrl or Command K','افتح دليل Biuret · Ctrl أو Command K'));close.setAttribute('aria-label',tr('Close guide','إغلاق الدليل'));
    badge.textContent=configured?'GEMINI':tr('BIURET SITE ASSISTANT','مساعد مواقع BIURET');
    intro.textContent=configured?tr('Ask in your own words. Gemini writes a fresh answer from public Biuret facts. Private administrator trial.','اسأل بطريقتك. يصيغ Gemini إجابة جديدة من معلومات Biuret العامة. تجربة خاصة للإدارة.'):checking?tr('Checking Gemini access…','جارٍ فحص الوصول إلى Gemini…'):tr('Gemini is currently a private administrator trial. Sign in with the approved account; page topics remain available to read.','Gemini تجربة خاصة للإدارة حالياً. سجّل دخولك بالحساب المعتمد؛ مواضيع الصفحات متاحة للقراءة.');
    contextLabel.textContent=tr('YOU ARE HERE','أنت هنا');contextName.textContent=(document.querySelector('main h1')?.textContent||document.title).replace(/\s+/g,' ').trim().slice(0,90);
    label.textContent=tr('Ask Gemini about Biuret','اسأل Gemini عن Biuret');input.placeholder=tr('Who owns the site? Compare paths, explain a tool…','مين صاحب الموقع؟ قارن مسارات، اشرح أداة…');send.textContent=busy?tr('Answering…','جارٍ الرد…'):tr('Ask Gemini','اسأل Gemini');send.disabled=busy||!core||!configured||checking;
    consentLabel.hidden=!configured;consentCopy.textContent=tr('Send this question and up to three recent successful questions to Google Gemini. Free Gemini may use inputs/replies for model improvement. No private data.','أرسل السؤال وحتى ثلاثة أسئلة سابقة ناجحة إلى Google Gemini. قد تستخدم الخدمة المجانية الأسئلة والردود لتحسين النموذج. لا تدخل بيانات خاصة.');
    suggestions.replaceChildren();for(const pair of questions[site]||questions.portfolio){const button=el('button');button.type='button';button.textContent=tr(...pair);button.disabled=busy;button.addEventListener('click',()=>fillQuestion(tr(...pair)));suggestions.append(button);}
    conversation.replaceChildren();if(!exchanges.length){const welcome=el('article','bg-welcome');const h=el('h3');h.textContent=tr('A conversation, not a saved reply.','محادثة، وإجابة بحسب سؤالك.');const p=el('p');p.textContent=tr('The model can explain public information across the Portfolio, Academy and Playground. Suggestions fill your question; they never send it automatically.','يشرح النموذج المعلومات العامة عن موقع الأعمال والأكاديمية وPlayground. الاقتراحات تملأ السؤال ولا ترسله تلقائياً.');welcome.append(h,p);
      for(const c of core?.contextCards(cards,site,location.pathname)||[]){const button=el('button','bg-read-topic');button.type='button';button.textContent=tr('Read page topic: ','اقرأ موضوع الصفحة: ')+c.title[locale()];button.addEventListener('click',()=>{exchanges.push({topic:c});render();});welcome.append(button);}conversation.append(welcome);}
    for(const x of exchanges){const block=el('article','bg-exchange');
      if(x.topic){const label=el('span','bg-response-label');label.textContent=tr('Page topic · reference text','موضوع الصفحة · نص مرجعي');const p=el('p');p.textContent=x.topic.body[locale()];block.append(label,p,sourceLink(x.topic));}
      else {const q=el('p','bg-question');q.dir='auto';q.textContent=x.question;block.append(q);const label=el('span','bg-response-label');label.textContent=x.remote?'Gemini':tr('No AI answer','لا توجد إجابة نموذج');block.append(label);const p=el('p');p.dir='auto';p.textContent=x.remote?.answer||tr(...notices[x.notice||'unavailable']);block.append(p);
        for(const c of x.matches||[])block.append(sourceLink(c));
        if(x.remote?.followups?.length){const next=el('div','bg-suggestions');for(const text of x.remote.followups){const b=el('button');b.type='button';b.dir='auto';b.textContent=text;b.disabled=busy;b.addEventListener('click',()=>fillQuestion(text));next.append(b);}block.append(next);}}
      conversation.append(block);}
    status.textContent=notices[state]?tr(...notices[state]):checking?tr('Checking access…','جارٍ فحص الوصول…'):configured?tr('Gemini connected · private trial','Gemini متصل · تجربة خاصة'):access==='restricted'?tr('Administrator sign-in required for Gemini.','يتطلب Gemini تسجيل الدخول بحساب الإدارة.'):tr('Gemini is unavailable in this tab. Open the private trial.','Gemini غير متاح في هذا التبويب. افتح التجربة الخاصة.');
    retry.textContent=state==='error'?tr('Reload Guide','أعد تحميل الدليل'):tr('Check connection','فحص الاتصال');retry.disabled=busy||checking;clear.textContent=tr('New conversation','محادثة جديدة');clear.disabled=busy;pilot.textContent=tr('Open full Guide ↗','افتح الدليل الكامل ↗');privacy.textContent=tr('Temporary conversation in this tab. No passwords, payment details or private reports. Google/Appwrite may retain submitted data.','محادثة مؤقتة في التبويب. لا ترسل كلمات مرور أو بيانات دفع أو تقارير خاصة. قد يحتفظ Google وAppwrite بالبيانات المرسلة.');hint.textContent=tr('Esc closes · Ctrl / ⌘ K opens','Esc للإغلاق · Ctrl / ⌘ K للفتح');
  }
  async function check(){if(!gateway||checking||busy)return;checking=true;configured=false;render();try{const result=await gateway.status();configured=result.configured===true;access=configured?'ready':'disabled';}catch(error){access=[401,403].includes(error.code)?'restricted':'unavailable';}finally{checking=false;render();}}
  async function ask(question){
    if(busy||!core||!configured||typeof question!=='string'||question.trim().length<2)return;
    if(!consent.checked){state='consent';render();consent.focus();return;}
    question=question.trim().slice(0,500);busy=true;state='search';render();const lang=locale();let reply=null,notice;
    const history=exchanges.filter(x=>x.remote).slice(-3).map(x=>({question:x.question,sourceIds:x.remote.sourceIds}));
    try{reply=readReply(await gateway.ask({question,locale:lang,site,consent:true,history}),cards);notice=reply?(reply.remote.outcome==='clarify'?'clarify':'remote'):'unknown';}
    catch(error){notice=error.code===429?'quota':'unavailable';if([401,403].includes(error.code)){configured=false;access='restricted';}}
    exchanges.push({question,...reply,notice});if(exchanges.length>10)exchanges.shift();input.value='';busy=false;state=notice;render();conversation.scrollTop=conversation.scrollHeight;input.focus();
  }
  function open(topic){render();if(!dialog.open){returnFocus=document.activeElement;dialog.showModal();launcher.setAttribute('aria-expanded','true');}input.focus();if(topic&&!core)pendingTopic=topic;if(topic&&core){const card=cards.find(c=>c.id===topic&&c.site===site);if(card)fillQuestion(card.title[locale()]);}if(gateway&&!configured)check();}
  launcher.addEventListener('click',()=>open());close.addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{launcher.setAttribute('aria-expanded','false');(returnFocus?.isConnected?returnFocus:launcher).focus();});
  dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});
  form.addEventListener('submit',e=>{e.preventDefault();ask(input.value);});clear.addEventListener('click',()=>{exchanges.length=0;input.value='';consent.checked=false;state='';render();input.focus();});
  document.addEventListener('biuret:guide-open',e=>open(typeof e.detail?.topic==='string'?e.detail.topic:''));
  document.addEventListener('keydown',e=>{if(e.defaultPrevented||e.altKey||e.shiftKey||!(e.ctrlKey||e.metaKey)||e.key.toLowerCase()!=='k')return;if(document.querySelector('dialog[open]')&&!dialog.open)return;e.preventDefault();open();});
  new MutationObserver(render).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
  async function load(){busy=true;state='loading';render();try{const suffix='?v=20261010-guide6'+(attempt++?'&retry='+attempt:'');const [module,transport,data]=await Promise.all([import(new URL('core.mjs'+suffix,asset)),import(new URL('gateway.mjs'+suffix,asset)),fetch(new URL('knowledge.json'+suffix,asset)).then(r=>{if(!r.ok)throw Error();return r.json();})]);if(!Array.isArray(data)||data.some(c=>!c.title?.en||!c.title?.ar||!c.body?.en||!c.body?.ar))throw Error('invalid');core=module;cards=data;gateway=transport.createGateway();readReply=transport.readReply;state='';}catch{state='error';}busy=false;render();if(core&&pendingTopic){const topic=pendingTopic;pendingTopic='';if(dialog.open)open(topic);}if(dialog.open)check();}
  retry.addEventListener('click',()=>state==='error'?load():check());load();
})();
